### ISSUE TITLE
Treefeller X Vane Plugin

### ISSUE THREAD

**Issue by BuilderDan** [IDev-mc/TreeFeller#2]
Hello, I am looking for compatibility with a plugin called Vane: https://modrinth.com/plugin/vane/version/v1.14.0
The plugin includes an Unbreakable enchantment, but when tested with Treefeller, it still took durability. I opened a discussion with the dev and this was the conversation:
![image](https://github.com/IDev-mc/TreeFeller/assets/19805371/90fd405a-660e-41f3-b198-5bb7cd2d24f4)

It'd be awesome if this could be looked into please

**Comment by BuilderDan** [comment]
Anything?

**Comment by IDev-mc** [comment]
hey, sorry for the late response. I'll take a look at it! Implementing it for 1.20

**Comment by IDev-mc** [comment]
Posted an update on [SpigotMC](https://www.spigotmc.org/resources/treefeller.84310/update?update=533757), that should fix your problems! Thanks for your help, let me know when you have further problems
