### ISSUE TITLE
Worledit leaves despawn

### ISSUE THREAD

**Issue by BarbokOL** [IDev-mc/TreeFeller#3]
Hello, I looked through the config and some of the documentation but couldn't find anything specific to this.

Im running the plugin on my multiplayer server and have a problem where leaves spawned via world edits _leaves, keep despawning.

Trying to build a giant Yggdrasil like tree and unable to.

**Comment by IDev-mc** [comment]
Hey,
are you experiencing issues with the decaying of leaves or the breaking of (wood of) the Tree?

**Comment by BarbokOL** [comment]
Hey,
Decaying of leaves that are created by worldedit. (no wood is being broken)

**Comment by IDev-mc** [comment]
Thank you for the clarification.
The decaying of leaves is not affected by the TreeFeller plugin. Furthermore, the only interaction of TreeFeller with leaves is related to the check of a wood block being part of a tree.

If you wish to disable the decay of leaves in generell please take a look at the LeavesDecayEvent: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/event/block/LeavesDecayEvent.html

Another way to disable decaying leaves is to set the randomTickSpeed to 0 (/gamerule randomTickSpeed 0). Depending on your servers use case this could severely influence the gameplay -> No growing crops... etc.

If you are looking to stop specific leaves from decaying, I would recommend using the WorldEdit API to set leaves to be persistent.

I hope this helps you!

**Comment by BarbokOL** [comment]
Thanks for the info!
